### ISSUE TITLE
Mermaid 显示异常

### ISSUE THREAD

**Issue by Crowds21** [zqhjl/Siyuan-Simple-OneDark#1]
在Atom One Dark 主题下使用mermaid 无法正常显示图片

## 文件内容

```markdown

graph TD
    	UsernamePasswordAuthenticationFIlter --未认证---> AuthenticationManager
	AuthenticationManager -- 委托--->AuthenticationProvider
	AuthenticationProvider -- 关联--- UserDetailsService
```

## Atom One Dark 
![image](https://user-images.githubusercontent.com/48215334/110058459-4b347a80-7d9d-11eb-8b30-0f1ec8da39e1.png)

## Mixture
![image](https://user-images.githubusercontent.com/48215334/110058502-5f787780-7d9d-11eb-9ad6-6e62389f70fa.png)

**Comment by svchord** [comment]
修复了，更新后可以查看。
> 虽然还是能看到有一丢丢边框，但是我看了下所有形状相近的子元素和父元素都没找到这个边框。
> 如果你能找到的话可以和我说一声。

**Comment by svchord** [comment]
哦等等，如果你说的是无法正常显示图片的话，应该不是主题的问题。我也发现偶尔会出现这种情况。一般来说重启就可以很好地显示了。
> 我还以为你是说这个label的底色有问题…
> ![image](https://user-images.githubusercontent.com/61345763/110123319-b90f8f00-7dfb-11eb-9075-413998e4e2c1.png)
