### ISSUE TITLE
段落间距过大

### ISSUE THREAD

**Issue by hkunzhe** [zqhjl/Siyuan-Simple-OneDark#2]
非常感谢作者提供的这个主题！使用起来非常地舒服，但是段落的间距/行距貌似比一般的主题要大很多？请问该如何调整，我不太懂前端 :)
![image](https://user-images.githubusercontent.com/30763967/117145787-1b7a1100-ade6-11eb-8a9d-ebc0efaaed02.png)
![image](https://user-images.githubusercontent.com/30763967/117145885-3482c200-ade6-11eb-9f6e-d403f8934834.png)

**Comment by svchord** [comment]
感谢喜欢！我猜这个应该是需要修改`<p>`标签和`<ul>`标签的外边距`margin`属性。你应该可以通过“段落块”和“大纲”关键词找到相应代码，具体操作我现在也没有时间去确认了，请见谅。

**Comment by hkunzhe** [comment]
好的，感谢
